---
language: python
python: 
  - "2.7"
  - "3.4"
  - "3.3"
  - "pypy"
install: 
  - pip install -r requirements.txt
script: 
  - export ANSIBLE_ROLES_PATH="../"
  - echo localhost > inventory
  - ansible-playbook -i inventory --syntax-check {{ cookiecutter.role_name }}.yml
  - ansible-playbook -i inventory --connection=local --sudo -vvvv {{ cookiecutter.role_name }}.yml